spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://dbserver_gedu_uc_test:3306/gedu_study_abroad?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: gedu_t_user
          password: KJHGFWQ$@#%$@b666xc
          driver-class-name: com.mysql.jdbc.Driver
          # 多数据源配置
          #multi-datasource1:
          #url: jdbc:mysql://localhost:3306/gedu-boot2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
          #username: root
          #password: root
          #driver-class-name: com.mysql.jdbc.Driver
  #redis 配置
  redis:
    database: 0
    host: dbserver_gedu_redis_test
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 30     #最大等待连接中的数量,设 0 为没有限制
        max-wait: 10000ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: M#$421#a!R%#$Vds
    port: 6377
    timeout: 10000ms #客户端超时时间单位是毫秒 默认是2000

  # 时间配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#MyBatis配置
mybatis:
  type-aliases-package: com.pxjy.**.domain.*
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/pxjy/**/mapper/*.xml


# DINGTALK
api:
  dingtalki:
    host: http://test.mci.ielts.cn/gedu_dingtalki
    port: 80
    examineCreate: /examine/create
    schoolUrl: [{schoolCode:006,host:"test.nantong.dingtalki.ielts.cn/gedu_dingtalki",port:80},{schoolCode:010,host:"test.shanghai.dingtalki.ielts.cn/gedu_dingtalki",port:80}]

# thrift 相关
thrift:
  serviceIp: test.thrift.ielts.cn
  servicePort: 7911
  minIdle: 30
  maxIdle: 100
  conTimeOut: 20000
  maxWait: 20000
  maxActive: 2000
#文档配置线上关闭
swagger2:
  enable: true
# 同步类型相关
studentApply:
  syncType:
    syncTypesInfo: 1&3-5, 2&4-5, 2&3-4, 1&3-23, 2&024@4-10, 1&026@4-10#4-50
    isAddReviewTypes: 3-5,4-5
